apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-simple-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RobertGrancsa/ci_cd_lab 
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # Automatically delete resources that are no longer defined in Git
      selfHeal: true   # Automatically correct any drift between your Git source and the deployed state
